<?php
/**
 * Custom posts for use with this theme
 *
 *
 */

// Register Custom Post Type
function custom_post_type() {
	// Register Testimonial Custom Post Type
	$labels = array(
		'name'                  => _x( 'Testimonials', 'testimonials', 'text_domain' ),
		'singular_name'         => _x( 'Testimonial', 'testimonial', 'text_domain' ),
		'menu_name'             => __( 'Testimonials', 'text_domain' ),
		'name_admin_bar'        => __( 'Testimonials', 'text_domain' ),
		'archives'              => __( 'Testimonials Archives', 'text_domain' ),
		'attributes'            => __( 'Testimonials Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Testimonials:', 'text_domain' ),
		'all_items'             => __( 'All Testimonials', 'text_domain' ),
		'add_new_item'          => __( 'Add Testimonial', 'text_domain' ),
		'add_new'               => __( 'Add Testimonial', 'text_domain' ),
		'new_item'              => __( 'New Testimonial', 'text_domain' ),
		'edit_item'             => __( 'Edit Testimonial', 'text_domain' ),
		'update_item'           => __( 'Update Testimonial', 'text_domain' ),
		'view_item'             => __( 'View Testimonial', 'text_domain' ),
		'view_items'            => __( 'View Testimonials', 'text_domain' ),
		'search_items'          => __( 'Search Testimonials', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Testimonial', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Testimonial', 'text_domain' ),
		'items_list'            => __( 'Testimonials list', 'text_domain' ),
		'items_list_navigation' => __( 'Testimonials list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Testimonials list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Testimonials', 'text_domain' ),
		'description'           => __( 'Testimonials post type', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title' ),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_in_rest'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'menu_icon'				=> 'dashicons-format-quote'
	);
	register_post_type( 'testimonial', $args );
	// Register Person Custom Post Type
	$labels = array(
		'name'                  => _x( 'People', 'people', 'text_domain' ),
		'singular_name'         => _x( 'Person', 'person', 'text_domain' ),
		'menu_name'             => __( 'People', 'text_domain' ),
		'name_admin_bar'        => __( 'People', 'text_domain' ),
		'archives'              => __( 'People Archives', 'text_domain' ),
		'attributes'            => __( 'People Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent People:', 'text_domain' ),
		'all_items'             => __( 'All People', 'text_domain' ),
		'add_new_item'          => __( 'Add Person', 'text_domain' ),
		'add_new'               => __( 'Add Person', 'text_domain' ),
		'new_item'              => __( 'New Person', 'text_domain' ),
		'edit_item'             => __( 'Edit Person', 'text_domain' ),
		'update_item'           => __( 'Update Person', 'text_domain' ),
		'view_item'             => __( 'View Person', 'text_domain' ),
		'view_items'            => __( 'View People', 'text_domain' ),
		'search_items'          => __( 'Search People', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Person', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Person', 'text_domain' ),
		'items_list'            => __( 'People list', 'text_domain' ),
		'items_list_navigation' => __( 'People list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter People list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'People', 'text_domain' ),
		'description'           => __( 'People post type', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'custom-fields', 'thumbnail' ),
		'hierarchical'          => true,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_in_rest'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'menu_icon'				=> 'dashicons-groups'
	);
	register_post_type( 'person', $args );	
	// Register Successes Custom Post Type
	$labels = array(
		'name'                  => _x( 'Successes', 'successes', 'text_domain' ),
		'singular_name'         => _x( 'Success', 'success', 'text_domain' ),
		'menu_name'             => __( 'Successes', 'text_domain' ),
		'name_admin_bar'        => __( 'Successes', 'text_domain' ),
		'archives'              => __( 'Successes Archives', 'text_domain' ),
		'attributes'            => __( 'Successes Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Successes:', 'text_domain' ),
		'all_items'             => __( 'All Successes', 'text_domain' ),
		'add_new_item'          => __( 'Add Success', 'text_domain' ),
		'add_new'               => __( 'Add Success', 'text_domain' ),
		'new_item'              => __( 'New Success', 'text_domain' ),
		'edit_item'             => __( 'Edit Success', 'text_domain' ),
		'update_item'           => __( 'Update Success', 'text_domain' ),
		'view_item'             => __( 'View Success', 'text_domain' ),
		'view_items'            => __( 'View Successes', 'text_domain' ),
		'search_items'          => __( 'Search Successes', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Success', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Success', 'text_domain' ),
		'items_list'            => __( 'Successes list', 'text_domain' ),
		'items_list_navigation' => __( 'Successes list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Successes list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Successes', 'text_domain' ),
		'description'           => __( 'Successes post type', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'custom-fields' ),
		'hierarchical'          => true,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_in_rest'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'menu_icon'				=> 'dashicons-format-status'
	);
	register_post_type( 'success', $args );
	// Register Videos Custom Post Type
	$labels = array(
		'name'                  => _x( 'Videos', 'videos', 'text_domain' ),
		'singular_name'         => _x( 'Video', 'video', 'text_domain' ),
		'menu_name'             => __( 'Videos', 'text_domain' ),
		'name_admin_bar'        => __( 'Videos', 'text_domain' ),
		'archives'              => __( 'Videos Archives', 'text_domain' ),
		'attributes'            => __( 'Videos Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Videos:', 'text_domain' ),
		'all_items'             => __( 'All Videos', 'text_domain' ),
		'add_new_item'          => __( 'Add Video', 'text_domain' ),
		'add_new'               => __( 'Add Video', 'text_domain' ),
		'new_item'              => __( 'New Video', 'text_domain' ),
		'edit_item'             => __( 'Edit Video', 'text_domain' ),
		'update_item'           => __( 'Update Video', 'text_domain' ),
		'view_item'             => __( 'View Video', 'text_domain' ),
		'view_items'            => __( 'View Videos', 'text_domain' ),
		'search_items'          => __( 'Search Videos', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Video', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Video', 'text_domain' ),
		'items_list'            => __( 'Videos list', 'text_domain' ),
		'items_list_navigation' => __( 'Videos list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Videos list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Videos', 'text_domain' ),
		'description'           => __( 'Videos post type', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'custom-fields', 'thumbnail' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_in_rest'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'post',
		'menu_icon'				=> 'dashicons-format-video',
		'rewrite'				=> array(
			'with_front'		=> false,
			'slug'				=> 'videos'
		)
	);
	register_post_type( 'video', $args );
}
add_action( 'init', 'custom_post_type', 0 );
